### ISSUE TITLE
Add build caching

### ISSUE THREAD

**Issue by wfaler** [chaordic-io/gbuild#5]
I think we can implement language independent build caching somewhat easily, by doing the following:

### Configure inputs and outputs of a cache
Something along the lines of the following on a `target`:

```
caches:
 - inputs: [project/Dependencies.scala, build.sbt]
    outputs: [..for scala, list of Coursier and Ivy directories for dependencies]
- inputs: [src]
   outputs: [target]
```

* We define things to be cached based on `inputs` and `output`, these are a list of files and/or directories.
* To get higher granularity/better chances of a cache-hit, we can have multiple caches for the same thing, for instance dependencies and sources separately for Scala, as above.
### Cache hit order

* checksum of inputs
* Last git hash
* First hit among last 5 git hashes

#### cache check logic
* get checksum
* check index for hit
* check local checksum for cache out
* if no local hit, get remote cache
* BUILD
* upload new cache if new checksum on ins, name is out-checksum.tar.gz

### Cache storage
Something along the lines of:

```
index/inputs/ # directory with files with name of checksum -> checksum of cache-output file
index/git/ # directory of files of git hash -> checksum (pointing to above file)
cache/ # directory of cache files, [hash].tar.gz
```

#### Storage implementations

* Local file storage
* S3/GCS (Use S3 API

### Other notes
* Cache config (in/out) lives on target
* rebuild strategy lives on execution-plan, so local/ci can be separate
